### ISSUE TITLE
Xogar does nothing

### ISSUE THREAD

**Issue by BlueRaja** [indyK1ng/Xogar#30]
This seems neat, but it doesn't seem to work for me.

OS: Windows 10
Setup: Running Steam from the normal directory on C:\, also have libraries in D:\ and E:\

When I start Xogar, it says "Xogar had trouble opening Steam in its default directory" then asks me to choose the directory.  After I do, it just closes itself with no feedback.  There's no output log that I can find.

**Comment by BlueRaja** [comment]
It works when I compile from source, so I imagine it's either a permissions issue _(though I tried "Run as Administrator" with no luck)_ or there's an issue with the latest uploaded version.

**Comment by indyK1ng** [comment]
Oh wow, I didn't know people still used this. It had seemed like it fell
flat.

Give me a few days to get everything set up. I may also have to set up a
Windows 7 VM to test it on to maintain compatibility.

**Comment by indyK1ng** [comment]
I just tested and confirmed that even running the installer as an administrator didn't help (it was something I thought of after my second cup of coffee). I can't say I'm too surprised - Windows 10 hadn't even been announced the last time I released a version.

I'm going to do some further investigating because I don't like that simply compiling from source appears to fix the issue - I have no clue if the forward incompatibility translates into a backwards incompatibility.

**Comment by BlueRaja** [comment]
What happens if you attach the VS Debugger to the running executable?

**Comment by BlueRaja** [comment]
Ok, mystery solved. The reason it doesn't happen when building from source is that [it's already been fixed](https://github.com/BlueRaja/Xogar/commit/380a6da59e264d0cb8d63bb8045968f2f5863210), but a new release was never uploaded.

**Comment by indyK1ng** [comment]
I am just the worst.

**Comment by indyK1ng** [comment]
Oh, and thank you for looking into it. I'll upload a new release tomorrow
so this doesn't happen again.

**Comment by BlueRaja** [comment]
No problem.  I know a lot of people who are interested in this, we just never knew it existed.

**Comment by indyK1ng** [comment]
I've tagged release 1.3.4 and uploaded an MSI for it. I may look into getting it added to Chocolatey Nuget's repository since I mostly use that to set up my new installs now.
